@startuml running-a-match

actor User
participant "CGArena Server" as Server
database DB
participant "CGArena Worker" as Worker

User -> Server ++ : Requests a match
Server -> DB : Persists the match (status = pending)
Server -> Server : Adds a match to the queue
Server -> User -- : OK

== Async ==

rnote over Server : Polls the match from the queue
rnote over Server : Decides where to run the match
note left of Server : Server maintains knowledge about workers and what they have
alt Embedded Worker
rnote over Server : Builds all the participants if not built yet
rnote over Server : Runs the match
Server -> DB : Persists the match results
else Worker1
Server -> Worker : (optional) Sends missing participants
Server -> Worker : Requests a match
Worker -> Server : Notifies about match completion and results
note right : can be batched
Server -> DB : Persists the match results
end
Server -> Worker : Sends the bot and builds if not there yet

@enduml