@startuml submitting-a-bot

actor User
participant Cli
participant API
participant Arena
database DB
participant Worker
participant Rating

User -> Cli ++ : Runs a command to add a bot
Cli -> API ++ : POST /api/bots
API -> Arena : Calls
Arena -> DB : Persists the bot
Arena --> Worker : event
Arena --> Rating : event
API -> Cli -- : OK
Cli -> User -- : OK

@enduml